### ISSUE TITLE
com.platon.crypto.Wallet.createStandard function does not support openjdk8

### ISSUE THREAD

**Issue by aviland** [PlatONnetwork/client-sdk-java#85]
com.platon.crypto.Wallet.createStandard function does not support openjdk8
```
java.lang.OutOfMemoryError: Java heap space

	at org.bouncycastle.util.Arrays.clone(Unknown Source)
	at org.bouncycastle.crypto.generators.SCrypt.SMix(Unknown Source)
	at org.bouncycastle.crypto.generators.SCrypt.MFcrypt(Unknown Source)
	at org.bouncycastle.crypto.generators.SCrypt.generate(Unknown Source)
	at com.platon.crypto.Wallet.generateDerivedScryptKey(Wallet.java:142)
	at com.platon.crypto.Wallet.create(Wallet.java:74)
	at com.platon.crypto.Wallet.createStandard(Wallet.java:93)
	at com.cicdi.jcli.util.WalletUtil.generateBip39Wallet(WalletUtil.java:180)
```

I tried  run the jar using openjdk14 and openjdk15,  everything goes well.
So it seems that com.platon.crypto.Wallet.createStandard function does not support openjdk8

**Comment by liushuyu1** [comment]
Hi,I tried to reproduce the problem you mentioned, but I failed. Can you provide more version information and code information?

java-version: openjdk version "1.8.0_302"
sdk-version: 0.15.1.14

Test:
```
@Test
    public void temp() throws Exception {
        String password = "000000";
        ECKeyPair ecKeyPair = Keys.createEcKeyPair();
        WalletFile standard = Wallet.createStandard(password,ecKeyPair);
        System.out.println(standard.getAddress());
    }
```
Result:
```
atp1mqcm86pdy4d7c3tn4zz3kru0xwnnz9unclypuh
```
